"""Unilog organizer adapter: raw input in, delivery contract out.

Deterministic only. No model, fuzzy matching, or content generation. Internal lexical
families are explicitly separate from organizer-authorized delivery classification.
"""

from .classification import (
    DEFAULT_FAMILY_RULES,
    DELIVERY_CLASSIFICATION_FIELDS,
    ClassificationAuthority,
    ClassificationDecision,
    ClassificationEvidence,
    ClassificationProposal,
    ClassificationReason,
    CuePattern,
    DeliveryClassificationProposal,
    DeliveryClassificationValues,
    DeterministicProductClassifier,
    InternalProductFamily,
    LexicalFamilyRule,
    OrganizerExampleCatalog,
    OrganizerExampleRule,
    load_organizer_example_catalog,
    organizer_example_rule,
    tokenize,
)
from .conformance import (
    ConformanceCode,
    ConformanceIssue,
    ConformanceReport,
    check_rows,
    check_schema,
)
from .delivery import (
    PASSTHROUGH_FIELDS,
    AttributeSlot,
    DeliveryRecord,
    record_from_raw_row,
    write_delivery_csv,
)
from .errors import (
    DeliverySchemaError,
    DuplicateColumn,
    InputSchemaError,
    MalformedRowError,
    MissingRequiredColumn,
    UnilogError,
    UnknownDeliveryField,
)
from .input import (
    REQUIRED_COLUMNS,
    RawProductRow,
    read_rows,
    read_unilog_input,
    validate_input_header,
)
from .manufacturer import ManufacturerParse, ParsedManufacturer, parse_part_manuf
from .normalization import (
    AuthorityLevel,
    AuthoritySource,
    CanonicalCatalog,
    CanonicalRule,
    DeterministicNormalizer,
    NormalizationDecision,
    NormalizationReason,
    NormalizationResult,
    NormalizationSubject,
    RawSignal,
    RowNormalization,
    reviewed_manufacturer_catalog,
)
from .placeholders import (
    BARE_HYPHEN_FIELDS,
    DOCUMENTED_PLACEHOLDERS,
    clean,
    is_placeholder,
)
from .schema import AttributeSlotSpec, DeliverySchema

__all__ = [
    "BARE_HYPHEN_FIELDS",
    "DEFAULT_FAMILY_RULES",
    "DELIVERY_CLASSIFICATION_FIELDS",
    "DOCUMENTED_PLACEHOLDERS",
    "PASSTHROUGH_FIELDS",
    "REQUIRED_COLUMNS",
    "AttributeSlot",
    "AttributeSlotSpec",
    "AuthorityLevel",
    "AuthoritySource",
    "CanonicalCatalog",
    "CanonicalRule",
    "ClassificationAuthority",
    "ClassificationDecision",
    "ClassificationEvidence",
    "ClassificationProposal",
    "ClassificationReason",
    "ConformanceCode",
    "ConformanceIssue",
    "ConformanceReport",
    "CuePattern",
    "DeliveryRecord",
    "DeliverySchema",
    "DeliverySchemaError",
    "DeliveryClassificationProposal",
    "DeliveryClassificationValues",
    "DeterministicProductClassifier",
    "DeterministicNormalizer",
    "DuplicateColumn",
    "InputSchemaError",
    "InternalProductFamily",
    "LexicalFamilyRule",
    "MalformedRowError",
    "ManufacturerParse",
    "MissingRequiredColumn",
    "NormalizationDecision",
    "NormalizationReason",
    "NormalizationResult",
    "NormalizationSubject",
    "OrganizerExampleCatalog",
    "OrganizerExampleRule",
    "ParsedManufacturer",
    "RawProductRow",
    "RawSignal",
    "RowNormalization",
    "UnilogError",
    "UnknownDeliveryField",
    "check_rows",
    "check_schema",
    "clean",
    "is_placeholder",
    "load_organizer_example_catalog",
    "organizer_example_rule",
    "parse_part_manuf",
    "read_rows",
    "read_unilog_input",
    "record_from_raw_row",
    "reviewed_manufacturer_catalog",
    "tokenize",
    "validate_input_header",
    "write_delivery_csv",
]
