"""Manufacturer source discovery and artifact acquisition.

A search result locates a candidate. It is never evidence. See ./README.md.
"""

from .acquire import (
    AcquiredArtifact,
    acquire_pdf,
    discovered_artifacts,
    source_metadata_for,
)
from .agent_search import (
    PROVIDER_NAME,
    PROVIDER_VERSION,
    AgentSearchConfig,
    AgentSearchConfigError,
    AgentSearchLimits,
    AgentSearchProvider,
    build_filter,
    corpus_pattern_for,
    included_patterns_for,
    query_site_pattern_for,
    reviewed_patterns_for_hint,
)
from .domains import (
    DEFAULT_REGISTRY_DIR,
    DomainRegistry,
    ManufacturerEntry,
    RegistryAuthority,
    host_covered_by,
    load_registry,
    normalize_host,
    normalize_manufacturer,
    parse_registry,
)
from .errors import (
    BudgetExceededError,
    DiscoveryError,
    FetchError,
    MalformedRegistryError,
    MalformedSearchResponseError,
    MissingSearchCredentialsError,
    RejectionReason,
    SearchBudgetExceededError,
    SearchProviderError,
    SearchProviderHTTPError,
    SearchProviderTimeout,
    SearchProviderTransportError,
    UnsafeUrlError,
)
from .fetch import (
    ACQUISITION_VERSION,
    HTML_CONTENT_TYPES,
    PDF_CONTENT_TYPES,
    USER_AGENT,
    FetchedResource,
    FetchPolicy,
    fetch_url,
    validate_url,
    validate_url_structure,
)
from .manual import (
    MANUAL_SOURCE_PROVIDER,
    MANUAL_SOURCE_QUERY,
    ManualLocatorKind,
    ManualSourceInput,
    ManualSourceMode,
    ManualSourceResult,
    ingest_manual_source,
    plan_manual_source,
)
from .models import (
    DISCOVERY_VERSION,
    CandidateStatus,
    DiscoveryRequest,
    DiscoveryResult,
    DiscoverySummary,
    MpnRelevance,
    SearchResult,
    SourceAuthority,
    SourceCandidate,
    SourceKind,
)
from .policy import (
    candidate_host,
    classify_authority,
    classify_kind,
    classify_relevance,
    host_of,
)
from .provider import (
    SearchCall,
    SearchExecution,
    SearchProvider,
    execute_search,
    execute_search_with_provenance,
)
from .query import QueryBudget, build_queries
from .ranking import rank_candidates, ranking_key, ranking_reasons
from .service import DiscoveryBudget, acquire_candidate, classify_candidate, discover_sources

__all__ = [
    "ACQUISITION_VERSION",
    "DEFAULT_REGISTRY_DIR",
    "DISCOVERY_VERSION",
    "HTML_CONTENT_TYPES",
    "MANUAL_SOURCE_PROVIDER",
    "MANUAL_SOURCE_QUERY",
    "PDF_CONTENT_TYPES",
    "PROVIDER_NAME",
    "PROVIDER_VERSION",
    "USER_AGENT",
    "AcquiredArtifact",
    "BudgetExceededError",
    "CandidateStatus",
    "DiscoveryBudget",
    "DiscoveryError",
    "DiscoveryRequest",
    "DiscoveryResult",
    "DiscoverySummary",
    "DomainRegistry",
    "FetchError",
    "FetchPolicy",
    "FetchedResource",
    "MalformedRegistryError",
    "MalformedSearchResponseError",
    "ManualLocatorKind",
    "ManualSourceInput",
    "ManualSourceMode",
    "ManualSourceResult",
    "ManufacturerEntry",
    "MissingSearchCredentialsError",
    "MpnRelevance",
    "AgentSearchConfig",
    "AgentSearchConfigError",
    "AgentSearchLimits",
    "AgentSearchProvider",
    "QueryBudget",
    "RegistryAuthority",
    "RejectionReason",
    "SearchBudgetExceededError",
    "SearchCall",
    "SearchExecution",
    "SearchProvider",
    "SearchProviderError",
    "SearchProviderHTTPError",
    "SearchProviderTimeout",
    "SearchProviderTransportError",
    "SearchResult",
    "SourceAuthority",
    "SourceCandidate",
    "SourceKind",
    "UnsafeUrlError",
    "acquire_pdf",
    "acquire_candidate",
    "candidate_host",
    "build_filter",
    "build_queries",
    "classify_authority",
    "classify_candidate",
    "classify_kind",
    "classify_relevance",
    "discover_sources",
    "discovered_artifacts",
    "execute_search",
    "execute_search_with_provenance",
    "fetch_url",
    "host_covered_by",
    "host_of",
    "corpus_pattern_for",
    "included_patterns_for",
    "ingest_manual_source",
    "query_site_pattern_for",
    "reviewed_patterns_for_hint",
    "load_registry",
    "normalize_host",
    "normalize_manufacturer",
    "parse_registry",
    "plan_manual_source",
    "rank_candidates",
    "ranking_key",
    "ranking_reasons",
    "source_metadata_for",
    "validate_url",
    "validate_url_structure",
]
